# Meta Data for SEO

## Homepage
title = "겨울학교"
titleSeparator = "-"
titleAddition = "2022 수치상대론 및 중력파 겨울학교 / 계산천체물리 경진대회"
description = "수치상대론과 중력파에 대한 심화 강의 및 실습을 위한 교육행사입니다."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["doks.png"]
ogLocale = "ko_KR"
domainTLD = "school.gw.nr.re.kr"
titleHome = "2022 수치상대론 및 중력파 겨울학교 / 계산천체물리 경진대회"

## Twitter Cards
twitterSite = "@nrgwloc"
twitterCreator = "@nrgwloc"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "2022 수치상대론 및 중력파 겨울학교 / 계산천체물리 경진대회"
schemaAuthor = "중력파 및 수치상대론 연구자 그룹"
schemaAuthorTwitter = "https://twitter.com/nrgwloc"
schemaAuthorLinkedIn = ""
schemaAuthorGitHub = "https://github.com/nrgw"
schemaLocale = "ko-KR"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/nrgwloc"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/nrgw"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Footer
footer = "Copyright © 수치상대론 및 중력파 겨울학교 조직위원회 <br> 이메일의 무단수집을 거부합니다."

# Feed
copyRight = "Copyright © 수치상대론 및 중력파 겨울학교 조직위원회ㄴ"

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\">Check out Doks v0.2</a>"

# Edit Page
docsRepo = "https://github.com/nrgw/doks-child-theme"
docsRepoBranch = "master"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = false
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  collapsibleSidebar = true
  multilingualMode = false
  docsVersioning = false
