[[docs]]
  name = "일반안내"
  weight = 10
  identifier = "general"
  url = "/docs/general/"

[[docs]]
  name = "강의"
  weight = 20
  identifier = "lecture"
  url = "/docs/lecture/"


[[docs]]
  name = "실습환경"
  weight = 30
  identifier = "aws"
  url = "/docs/aws/"


# [[docs]]
#   name = "Prologue"
#   weight = 50
#   identifier = "prologue"
#   url = "/docs/prologue/"

# [[docs]]
#   name = "도움"
#   weight = 60
#   identifier = "help"
#   url = "/docs/help/"

[[main]]
  name = "행사안내"
  url = "/docs/general/program/"
  weight = 10

[[main]]
  name = "공지사항"
  url = "/blog/"
  weight = 20

[[main]]
  name = "관련사이트"
  url = "/sites/"
  weight = 30

[[main]]
  name = "문의"
  url = "/contact/"
  weight = 40

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/nrgwloc"
  weight = 10

[[social]]
  name = "Instagram"
  pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>'
  url = "https://instagram.com/nrgwloc/"
  weight = 20

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/nrgw"
  post = "v0.1.0"
  weight = 30

[[footer]]
  name = "개인정보 처리방침"
  url = "/privacy-policy/"
  weight = 10
